name: Main

on:
  push:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Get Latest Forge CLI Release
        id: version
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/laravel/forge-cli/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(curl -sL https://api.github.com/repos/vtalbot/forge-cli-ci/releases/latest | jq -r ".tag_name")
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Forge CLI Docker
        if: steps.version.outputs.current_tag != steps.version.outputs.release_tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            version=${{ steps.version.outputs.release_tag }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/forge-cli:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/forge-cli:${{ steps.version.outputs.release_tag }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.release_tag }}
          release_name: ${{ steps.version.outputs.release_tag }}
          draft: false
          prerelease: false
